[relaychain]
chain = "rococo-local"

[settings]
provider = "native"

[[relaychain.nodes]]
name = "alice"
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[parachains]]
id = 100
default_command = "./target/release/parachain-template-node"

[[parachains.collators]]
name = "collator-01"
